### ISSUE TITLE
Circular dependencies & webpack

### ISSUE THREAD

**Issue by MerlinB** [sCrypt-Inc/scryptlib#76]
There are a few circular imports in scryptlib that lead to problems when including it in a webpack build.

1) abi.ts > compilerWrapper.ts > contract.ts
2) compilerWrapper.ts > contract.ts
3) compilerWrapper.ts > contract.ts > scryptTypes.ts
4) compilerWrapper.ts > contract.ts > scryptTypes.ts > utils.ts
5) scryptTypes.ts > utils.ts

**Comment by zhfnjust** [comment]
hello, i use webpack to build a scryptlib min js, but it didnot report any error, my branch is https://github.com/sCrypt-Inc/scryptlib/tree/feature/web3
10:13
can you show me how make webpack report error?

**Comment by zhfnjust** [comment]
cannot  reproduce this issue
